<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\Models\Item as Item;


class ItemTableSeeder extends Seeder {
	public function run(){
		//Item::truncate();
		Item::create(['id'=>1,   'testo' =>'Mi piacciono le riviste di meccanica']);
		Item::create(['id'=>2,   'testo' =>'Ho un buon appetito']);
		Item::create(['id'=>3,   'testo' =>'Penso che mi piacerebbe lavorare come bibliotecario']);
		Item::create(['id'=>4,   'testo' =>'La mia vita di ogni giorno è piena di cose che mi interessano']);
		Item::create(['id'=>5,   'testo' =>'A volte ho desiderato molto andare via da casa']);
		Item::create(['id'=>6,   'testo' =>'Mi riesce difficile concentrarmi su un compito o su un lavoro']);
		Item::create(['id'=>7,   'testo' =>'Mia madre è una buona persona, o (se Sua madre è morta) è stata una buona persona']);
		Item::create(['id'=>8,   'testo' =>'Quando ho un problema mi è di aiuto parlarne con qualcuno']);
		Item::create(['id'=>9,   'testo' =>'Spesso mi sento in colpa perché fingo di essere più dispiaciuto per qualcosa di quanto lo sia veramente']);
		Item::create(['id'=>10,  'testo' =>'Bisogna discutere molto con la maggior parte della gente per convincerla della verità']);
		Item::create(['id'=>11,  'testo' =>'Mi piace andare a ballare']);
		Item::create(['id'=>12,  'testo' =>'Spesso sento di poter leggere nella mente degli altri']);
		Item::create(['id'=>13,  'testo' =>'A volte insisto fino a che gli altri perdono la pazienza con me']);
		Item::create(['id'=>14,  'testo' =>'A volte sono posseduto dagli spiriti maligni']);
		Item::create(['id'=>15,  'testo' =>'Molto spesso mi sembra di avere un nodo alla gola']);
		Item::create(['id'=>16,  'testo' =>'A volte mi viene voglia di imprecare']);
		Item::create(['id'=>17,  'testo' =>'Sono una persona molto socievole']);
		Item::create(['id'=>18,  'testo' =>'Molto spesso mi sento fiacco']);
		Item::create(['id'=>19,  'testo' =>'I miei familiari e i miei parenti stretti vanno molto d\'accordo']);
		Item::create(['id'=>20,  'testo' =>'Mi sento a disagio nei luoghi chiusi']);
		Item::create(['id'=>21,  'testo' =>'Qualche volta, da ragazzo, ho rubato delle cose']);
		Item::create(['id'=>22,  'testo' =>'Vorrei essere felice così come sembrano esserlo gli altri']);
		Item::create(['id'=>23,  'testo' =>'A volte mi vien voglia di fracassare qualcosa']);
		Item::create(['id'=>24,  'testo' =>'Vengo facilmente vinto nelle discussioni']);
		Item::create(['id'=>25,  'testo' =>'Sono capace di lavorare come lo sono sempre stato']);
		Item::create(['id'=>26,  'testo' =>'Quando uno mi fa un torto, sento che dovrei fargliela pagare, se possibile, magari solo per principio']);
		Item::create(['id'=>27,  'testo' =>'Spesso ho perduto delle occasioni perché non riuscivo a decidermi abbastanza rapidamente']);
		Item::create(['id'=>28,  'testo' =>'Di solito ho le mani e i piedi abbastanza caldi']);
		Item::create(['id'=>29,  'testo' =>'Le delusioni mi colpiscono così intensamente da non potermele togli ere dalla mente']);
		Item::create(['id'=>30,  'testo' =>'Di solito sono malinconico']);
		Item::create(['id'=>31,  'testo' =>'Mi riesce difficile capire bene come una volta quello che leggo']);
		Item::create(['id'=>32,  'testo' =>'Ho avuto esperienze molto strane e insolite']);
		Item::create(['id'=>33,  'testo' =>'Ho quasi sempre la tosse']);
		Item::create(['id'=>34,  'testo' =>'Fantasmi o spiriti possono influenzare le persone sia nel bene che nel male']);
		Item::create(['id'=>35,  'testo' =>'Devo lottare frequentemente per non mostrare la mia timidezza']);
		Item::create(['id'=>36,  'testo' =>'Penso che moltissime persone esagerino le proprie disgrazie per ottenere la simpatia e l\'aiuto degli altri']);
		Item::create(['id'=>37,  'testo' =>'Non sono ferito facilmente nei miei sentimenti']);
		Item::create(['id'=>38,  'testo' =>'Mai mi sono trovato nei guai a causa del mio comportamento sessuale']);
		Item::create(['id'=>39,  'testo' =>'Spesso ho dovuto prendere ordini da qualcuno che ne sapeva meno di me']);
		Item::create(['id'=>40,  'testo' =>'Me ne starei quasi sempre a sognare ad occhi aperti piuttosto che fare qualsiasi altra cosa']);
		Item::create(['id'=>41,  'testo' =>'Qualche volta provo piacere a far del male alle persone cui voglio bene']);
		Item::create(['id'=>42,  'testo' =>'Mi piacerebbe essere un soldato']);
		Item::create(['id'=>43,  'testo' =>'Soffro di attacchi di nausea e di vomito']);
		Item::create(['id'=>44,  'testo' =>'Mi riesce difficile attaccare discorso con persone che ho appena conosciuto']);
		Item::create(['id'=>45,  'testo' =>'Non sempre dico la verità']);
		Item::create(['id'=>46,  'testo' =>'Quando sono con la gente, sono disturbato dal fatto di udire cose molto strane']);
		Item::create(['id'=>47,  'testo' =>'Mi piace andare a feste e trattenimenti dove c\'è molto chiasso e divertimento']);
		Item::create(['id'=>48,  'testo' =>'Mi manca proprio la fiducia in me stesso']);
		Item::create(['id'=>49,  'testo' =>'Mi è piaciuto fumare marijuana']);
		Item::create(['id'=>50,  'testo' =>'Mi piacerebbe essere un cantante']);
		Item::create(['id'=>51,  'testo' =>'Sono stato spaventato da persone o cose, pur sapendo che non mi potevano fare del male']);
		Item::create(['id'=>52,  'testo' =>'Molto raramente soffro di stitichezza']);
		Item::create(['id'=>53,  'testo' =>'A volte mi sento pieno di energie']);
		Item::create(['id'=>54,  'testo' =>'I fulmini sono una delle mie paure']);
		Item::create(['id'=>55,  'testo' =>'Penso che la maggior parte delle persone mentirebbe per farsi strada nella vita']);
		Item::create(['id'=>56,  'testo' =>'Divento ansioso e turbato quando devo allontanarmi da casa per un breve viaggio']);
		Item::create(['id'=>57,  'testo' =>'Mi piacciono i trattenimenti e le feste proprio per stare in mezzo alla gente']);
		Item::create(['id'=>58,  'testo' =>'Qualcuno della mia famiglia ha abitudini che mi irritano moltissimo']);
		Item::create(['id'=>59,  'testo' =>'La mia memoria sembra buona']);
		Item::create(['id'=>60,  'testo' =>'Spesso trovo necessario prendere posizione per sostenere ciò che ritengo giusto']);
		Item::create(['id'=>61,  'testo' =>'Mai ho fatto qualcosa di pericoloso per il gusto di farlo']);
		Item::create(['id'=>62,  'testo' =>'Faccio molte cose di cui dopo mi pento (più di quanto sembra lo facciano gli altri)']);
		Item::create(['id'=>63,  'testo' =>'Spesso mi è sembrato che sconosciuti mi osservassero con occhio critico']);
		Item::create(['id'=>64,  'testo' =>'Sono una persona importante']);
		Item::create(['id'=>65,  'testo' =>'Non soffro quasi mai di dolori nella regione del cuore o al torace']);
		Item::create(['id'=>66,  'testo' =>'A scuola, talvolta, sono stato mandato dal preside per cattiva condotta']);
		Item::create(['id'=>67,  'testo' =>'Mi dà fastidio avere gente intorno']);
		Item::create(['id'=>68,  'testo' =>'Di solito mi devo fermare a pensarci sopra prima di fare qualcosa, anche se di poca importanza']);
		Item::create(['id'=>69,  'testo' =>'Le mie mani non sono diventate pesanti o impacciate nei movimenti']);
		Item::create(['id'=>70,  'testo' =>'Non tutti i giorni leggo l\'articolo di fondo del giornale']);
		Item::create(['id'=>71,  'testo' =>'Credo che si stia complottando contro di me']);
		Item::create(['id'=>72,  'testo' =>'A volte i miei pensieri si susseguono così rapidamente che non riesco ad esprimerli']);
		Item::create(['id'=>73,  'testo' =>'Non credo di essere più nervoso degli altri']);
		Item::create(['id'=>74,  'testo' =>'Molto spesso mi sembra di aver fatto qualcosa di sbagliato o di cattivo']);
		Item::create(['id'=>75,  'testo' =>'Penso che mi piacerebbe fare il tipo di lavoro che fa una guardia forestale']);
		Item::create(['id'=>76,  'testo' =>'Ho disturbi di stomaco diverse volte alla settimana']);
		Item::create(['id'=>77,  'testo' =>'Sono così sensibile riguardo a certi argomenti da non poterne parlare']);
		Item::create(['id'=>78,  'testo' =>'Il mio udito mi sembra buono come quello della maggior parte della gente']);
		Item::create(['id'=>79,  'testo' =>'Spesso la notte ho degli incubi']);
		Item::create(['id'=>80,  'testo' =>'Ho pochissimi litigi con i miei familiari']);
		Item::create(['id'=>81,  'testo' =>'A volte scoppio a ridere o a piangere senza riuscire a controllarmi']);
		Item::create(['id'=>82,  'testo' =>'I serpenti mi fanno poca o nessuna impressione']);
		Item::create(['id'=>83,  'testo' =>'Generalmente sento che la mia vita merita di essere vissuta']);
		Item::create(['id'=>84,  'testo' =>'A volte vorrei attaccar briga e fare a pugni con qualcuno']);
		Item::create(['id'=>85,  'testo' =>'Mai ho avuto visioni']);
		Item::create(['id'=>86,  'testo' =>'Riesco ad esprimere i miei veri sentimenti solo quando bevo']);
		Item::create(['id'=>87,  'testo' =>'La maggior parte della gente è onesta soprattutto per paura di essere scoperta']);
		Item::create(['id'=>88,  'testo' =>'Raramente soffro di dolori dietro al collo']);
		Item::create(['id'=>89,  'testo' =>'A volte mi sento proprio inutile']);
		Item::create(['id'=>90,  'testo' =>'Mi fa paura trovarmi in uno stanzino o in un altro luogo chiuso e stretto']);
		Item::create(['id'=>91,  'testo' =>'Mi imbarazzo facilmente']);
		Item::create(['id'=>92,  'testo' =>'Credo di essere pedinato']);
		Item::create(['id'=>93,  'testo' =>'Recentemente ho pensato di suicidarmi']);
		Item::create(['id'=>94,  'testo' =>'Non mi preoccupa incontrare estranei']);
		Item::create(['id'=>95,  'testo' =>'Ogni tanto rimando a domani quello che dovrei fare oggi']);
		Item::create(['id'=>96,  'testo' =>'I miei genitori spesso si opponevano al tipo di gente che frequentavo']);
		Item::create(['id'=>97,  'testo' =>'Mi piace conoscere persone importanti perché mi fa sentire importante']);
		Item::create(['id'=>98,  'testo' =>'Voglio bene a mio padre, o (se Suo padre è morto) ho voluto bene a mio padre']);
		Item::create(['id'=>99,  'testo' =>'La maggior parte delle persone userebbe mezzi sleali per avere un profitto o un vantaggio piuttosto che perderlo']);
		Item::create(['id'=>100, 'testo' =>'Mi piacciono le poesie']);
		Item::create(['id'=>101, 'testo' =>'Quasi sempre mi sembra che la testa mi faccia male dappertutto']);
		Item::create(['id'=>102, 'testo' =>'Mi sembra di essere capace e sveglio quanto la maggior parte delle persone che mi circonda']);
		Item::create(['id'=>103, 'testo' =>'Talvolta mi capita di odiare qualcuno della mia famiglia al quale di solito voglio bene']);
		Item::create(['id'=>104, 'testo' =>'Di solito difendo con forza le mie opinioni']);
		Item::create(['id'=>105, 'testo' =>'Sono quasi sempre contento']);
		Item::create(['id'=>106, 'testo' =>'Ho avuto periodi in cui svolgevo delle attività senza poi ricordarmi di ciò che avevo fatto']);
		Item::create(['id'=>107, 'testo' =>'Mi piace parlare di sesso']);
		Item::create(['id'=>108, 'testo' =>'Parecchie volte ho rinunciato a fare qualcosa perché credevo di non esserne capace']);
		Item::create(['id'=>109, 'testo' =>'Mi piace l\'animazione della folla']);
		Item::create(['id'=>110, 'testo' =>'Sento di essere stato spesso punito senza ragione']);
		Item::create(['id'=>111, 'testo' =>'Penso che mi piacerebbe lavorare come costruttore edile']);
		Item::create(['id'=>112, 'testo' =>'Mi può capitare di rinunciare a fare qualcosa, se gli altri mi dicono che la sto facendo male']);
		Item::create(['id'=>113, 'testo' =>'Soffro poco o niente di spasmi o tremori muscolari']);
		Item::create(['id'=>114, 'testo' =>'Vorrei non essere così timido']);
		Item::create(['id'=>115, 'testo' =>'Non ho paura del fuoco']);
		Item::create(['id'=>116, 'testo' =>'Ho la tendenza a vedere le cose più difficili di quello che sono']);
		Item::create(['id'=>117, 'testo' =>'C\'è qualcosa che non va nella mia mente']);
		Item::create(['id'=>118, 'testo' =>'Mi piace flirtare, amoreggiare']);
		Item::create(['id'=>119, 'testo' =>'Perdo facilmente la pazienza con le persone']);
		Item::create(['id'=>120, 'testo' =>'Quasi sempre vorrei essere morto']);
		Item::create(['id'=>121, 'testo' =>'È meglio non fidarsi di nessuno']);
		Item::create(['id'=>122, 'testo' =>'Ho avuto crisi in cui non potevo controllare i miei movimenti o la parola, ma capivo quello che succedeva intorno a me']);
		Item::create(['id'=>123, 'testo' =>'Mi preoccupo abbastanza per le disgrazie che potrebbero capitare']);
		Item::create(['id'=>124, 'testo' =>'Mai sono stato innamorato di qualcuno']);
		Item::create(['id'=>125, 'testo' =>'Il mio modo di parlare è lo stesso di sempre (né più veloce, né più lento, né male articolato, né rauco)']);
		Item::create(['id'=>126, 'testo' =>'Mi piaceva andare a scuola']);
		Item::create(['id'=>127, 'testo' =>'A volte mi arrabbio']);
		Item::create(['id'=>128, 'testo' =>'Non mi disturba maneggiare il denaro']);
		Item::create(['id'=>129, 'testo' =>'Qualcuno ha cercato di avvelenarmi']);
		Item::create(['id'=>130, 'testo' =>'Passo molto tempo a rimuginare']);
		Item::create(['id'=>131, 'testo' =>'Quando mi annoio mi piace trovare qualche cosa di eccitante da fare']);
		Item::create(['id'=>132, 'testo' =>'Spesso attraverso la strada per evitare di incontrare qualcuno che ho visto']);
		Item::create(['id'=>133, 'testo' =>'Ogni cosa ha per me lo stesso sapore']);
		Item::create(['id'=>134, 'testo' =>'Non mi arrabbio facilmente']);
		Item::create(['id'=>135, 'testo' =>'Mi dà molto fastidio pensare di fare dei cambiamenti nella mia vita']);
		Item::create(['id'=>136, 'testo' =>'Mi è impossibile mantenere l\'attenzione su una data cosa']);
		Item::create(['id'=>137, 'testo' =>'Mi sembra quasi sempre di avere come un senso di pesantezza alla testa o al naso']);
		Item::create(['id'=>138, 'testo' =>'I miei genitori e i miei familiari trovano in me più difetti di quanto dovrebbero']);
		Item::create(['id'=>139, 'testo' =>'Spesso sento voci senza sapere da dove provengono']);
		Item::create(['id'=>140, 'testo' =>'Mi piacciono diversi tipi di gioco e svago']);
		Item::create(['id'=>141, 'testo' =>'Ho fatto uso eccessivo di bevande alcoliche']);
		Item::create(['id'=>142, 'testo' =>'La maggior parte delle persone si fa degli amici perché possono risultare utili']);
		Item::create(['id'=>143, 'testo' =>'Talvolta ho ostacolato persone che tentavano di fare qualcosa non perché me ne importasse molto, ma per una questione di principio']);
		Item::create(['id'=>144, 'testo' =>'Trovo difficoltà nel cominciare a fare le cose']);
		Item::create(['id'=>145, 'testo' =>'Mi piacerebbe essere un fioraio']);
		Item::create(['id'=>146, 'testo' =>'Quasi ogni giorno capita qualcosa che mi spaventa']);
		Item::create(['id'=>147, 'testo' =>'Mi piace che la gente sappia come la penso']);
		Item::create(['id'=>148, 'testo' =>'Mi piace molto andare a caccia']);
		Item::create(['id'=>149, 'testo' =>'A volte pensieri di poca o nessuna importanza si fissano nella mia mente e mi disturbano per giorni interi']);
		Item::create(['id'=>150, 'testo' =>'Qualcuno ha cercato di derubarmi']);
		Item::create(['id'=>151, 'testo' =>'Le bufere mi terrorizzano']);
		Item::create(['id'=>152, 'testo' =>'Mi vien voglia di rinunciare subito a quello che sto facendo quando le cose vanno male']);
		Item::create(['id'=>153, 'testo' =>'Le mie preoccupazioni sembrano svanire quando mi trovo in un gruppo di amici pieni di vita']);
		Item::create(['id'=>154, 'testo' =>'A casa, non mi comporto così bene a tavola, come quando mangio fuori in compagnia']);
		Item::create(['id'=>155, 'testo' =>'Mi arrabbio facilmente e poi mi passa presto']);
		Item::create(['id'=>156, 'testo' =>'Ricordo di aver fatto finta di essere ammalato per evitare qualche impegno']);
		Item::create(['id'=>157, 'testo' =>'Chiunque sia capace e abbia voglia di lavorare sodo ha buone possibilità di successo']);
		Item::create(['id'=>158, 'testo' =>'La vita è quasi sempre una fatica per me']);
		Item::create(['id'=>159, 'testo' =>'Ho avuto dei momenti di vuoto, in cui le mie attività venivano interrotte e non capivo che cosa succedeva intorno a me']);
		Item::create(['id'=>160, 'testo' =>'A volte sento di poter prendere decisioni con una insolita facilità']);
		Item::create(['id'=>161, 'testo' =>'Mi vengono in mente parole cattive o perfino terribili e non riesco a liberarmene']);
		Item::create(['id'=>162, 'testo' =>'Raramente o mai ho sofferto di vertigini']);
		Item::create(['id'=>163, 'testo' =>'Mi sveglio fresco e riposato quasi tutte le mattine']);
		Item::create(['id'=>164, 'testo' =>'Ultimamente ho pensato molto al suicidio']);
		Item::create(['id'=>165, 'testo' =>'Spesso ho paura del buio']);
		Item::create(['id'=>166, 'testo' =>'A volte, senza nessuna ragione o perfino quando le cose mi vanno male, mi sento così eccitato e felice da "toccare il cielo con un dito"']);
		Item::create(['id'=>167, 'testo' =>'Dover aspettare mi rende nervoso']);
		Item::create(['id'=>168, 'testo' =>'Ci sono persone che tentano di rubarmi i pensieri e le idee']);
		Item::create(['id'=>169, 'testo' =>'Il futuro mi sembra senza speranza']);
		Item::create(['id'=>170, 'testo' =>'Posso dormire durante il giorno ma non di notte']);
		Item::create(['id'=>171, 'testo' =>'Penso che chiunque direbbe una bugia per tirarsi fuori dai guai']);
		Item::create(['id'=>172, 'testo' =>'Spesso, anche se tutto mi va bene, sento che non mi importa di niente']);
		Item::create(['id'=>173, 'testo' =>'Sono stato picchiato spesso quando ero bambino']);
		Item::create(['id'=>174, 'testo' =>'Durante gli ultimi anni sono stato bene per la maggior parte del tempo']);
		Item::create(['id'=>175, 'testo' =>'Non sono mai così felice come quando sono solo']);
		Item::create(['id'=>176, 'testo' =>'Spesso sento come se avessi un cerchio stretto intorno alla testa']);
		Item::create(['id'=>177, 'testo' =>'Di solito evito di parlare per primo agli altri']);
		Item::create(['id'=>178, 'testo' =>'Sarebbe meglio se quasi tutte le leggi venissero eliminate']);
		Item::create(['id'=>179, 'testo' =>'A volte perdo o cambio la voce anche se non ho il raffreddore']);
		Item::create(['id'=>180, 'testo' =>'Qualcuno della mia famiglia ha fatto cose che mi hanno spaventato']);
		Item::create(['id'=>181, 'testo' =>' Almeno una volta alla settimana, o più spesso, divento molto eccitato']);
		Item::create(['id'=>182, 'testo' =>'Ho piena fiducia in me stesso']);
		Item::create(['id'=>183, 'testo' =>'Preferisco vincere piuttosto che perdere in un gioco']);
		Item::create(['id'=>184, 'testo' =>'Non ho paura dell\'acqua']);
		Item::create(['id'=>185, 'testo' =>'La maggior parte della gente, in fondo, si scomoda malvolentieri per aiutare il prossimo']);
		Item::create(['id'=>186, 'testo' =>'Mai ho avuto attacchi improvvisi o convulsioni']);
		Item::create(['id'=>187, 'testo' =>'Qualche volta mi è sembrato che le difficoltà si accumulassero talmente da non poterle superare']);
		Item::create(['id'=>188, 'testo' =>'Se fossi un giornalista mi piacerebbe molto fare il cronista sportivo']);
		Item::create(['id'=>189, 'testo' =>'Poche volte ho mal di testa']);
		Item::create(['id'=>190, 'testo' =>'Mai ho avuto guai con la legge']);
		Item::create(['id'=>191, 'testo' =>'Quando cammino sto molto attento a non calpestare le fessure sul marciapiede']);
		Item::create(['id'=>192, 'testo' =>'Dopo una brutta giornata di solito ho bisogno di bere qualche bicchierino per rilassarmi']);
		Item::create(['id'=>193, 'testo' =>'A volte sono rimasto così colpito dall\' abilità di qualche criminale, che ho sperato che gli andasse bene']);
		Item::create(['id'=>194, 'testo' =>'Sono sicuro che si fanno chiacchiere su di me']);
		Item::create(['id'=>195, 'testo' =>'Qualcosa di emozionante o di eccitante mi solleva quasi sempre il morale quando sono triste']);
		Item::create(['id'=>196, 'testo' =>'Mi piace il teatro']);
		Item::create(['id'=>197, 'testo' =>'Di solito parlo molto chiaramente a quelli che sto cercando di correggere o migliorare']);
		Item::create(['id'=>198, 'testo' =>'Tendo a tirarmi indietro di fronte a situazioni critiche o difficili']);
		Item::create(['id'=>199, 'testo' =>'A volte sento strani odori']);
		Item::create(['id'=>200, 'testo' =>'Ho più difficoltà degli altri a concentrarmi']);
		Item::create(['id'=>201, 'testo' =>'Mi piacciono le feste e i trattenimenti']);
		Item::create(['id'=>202, 'testo' =>'Mai mi sono sentito bene come adesso nella mia vita']);
		Item::create(['id'=>203, 'testo' =>'Qualche volta la mia anima lascia il mio corpo']);
		Item::create(['id'=>204, 'testo' =>'Mi sento spesso solo, anche quando sono in mezzo alla gente']);
		Item::create(['id'=>205, 'testo' =>'Da ragazzo spesso non andavo a scuola anche quando ci sarei dovuto andare']);
		Item::create(['id'=>206, 'testo' =>'Vorrei smettere di preoccuparmi per cose che ho detto e che possono aver ferito i sentimenti di qualcuno']);
		Item::create(['id'=>207, 'testo' =>'Ho dei periodi in cui mi sento insolitamente allegro senza particolari motivi']);
		Item::create(['id'=>208, 'testo' =>'Ho paura di usare coltelli o altri oggetti molto taglienti o appuntiti']);
		Item::create(['id'=>209, 'testo' =>'Ho avuto certamente più motivi di preoccupazione di quanti me ne spettassero']);
		Item::create(['id'=>210, 'testo' =>'Sono disturbato da pesantezza di stomaco due o tre volte alla settimana, o anche più spesso']);
		Item::create(['id'=>211, 'testo' =>'Non mi piace ogni persona che conosco']);
		Item::create(['id'=>212, 'testo' =>'Non ho nemici che vogliano veramente farmi del male']);
		Item::create(['id'=>213, 'testo' =>'Generalmente la gente esige più rispetto per i propri diritti di quanto sia disposta a concederne']);
		Item::create(['id'=>214, 'testo' =>'Sebbene non sia felice della vita che conduco, non c\'è niente che io possa fare']);
		Item::create(['id'=>215, 'testo' =>'Sono spesso in serio disaccordo con le persone che mi sono affettivamente vicine']);
		Item::create(['id'=>216, 'testo' =>'A volte il mio udito è così sensibile che mi dà fastidio']);
		Item::create(['id'=>217, 'testo' =>'Molto raramente ho momenti di malinconia o tristezza']);
		Item::create(['id'=>218, 'testo' =>'A volte è stato per me impossibile trattenermi dal rubare o portar via qualcosa in un negozio']);
		Item::create(['id'=>219, 'testo' =>'A volte sono così eccitato che mi riesce difficile addormentarmi']);
		Item::create(['id'=>220, 'testo' =>'Non ho paura dei ragni']);
		Item::create(['id'=>221, 'testo' =>'Credo che bisogna far rispettare rigorosamente la legge']);
		Item::create(['id'=>222, 'testo' =>'Mi sembra di fare amicizia rapidamente come gli altri']);
		Item::create(['id'=>223, 'testo' =>'Sono stato sospeso da scuola una o più volte per cattiva condotta']);
		Item::create(['id'=>224, 'testo' =>'Ho sempre troppo poco tempo per portare a termine ciò che devo fare']);
		Item::create(['id'=>225, 'testo' =>'Mi è stato detto che cammino durante il sonno']);
		Item::create(['id'=>226, 'testo' =>'Mi piacerebbe fare il pilota di auto da corsa']);
		Item::create(['id'=>227, 'testo' =>'Non ho difficoltà nel mantenere l\'equilibrio mentre cammino']);
		Item::create(['id'=>228, 'testo' =>'Quasi sempre sto in ansia per qualcuno o per qualcosa']);
		Item::create(['id'=>229, 'testo' =>'Di solito rinuncio ad eseguire un progetto se gli altri pensano che non ne valga la pena']);
		Item::create(['id'=>230, 'testo' =>'Ho molti disturbi di stomaco']);
		Item::create(['id'=>231, 'testo' =>'Riesco facilmente a intimorire gli altri e qualche volta lo faccio per il gusto di farlo']);
		Item::create(['id'=>232, 'testo' =>'Talvolta penso di essere un buono a nulla']);
		Item::create(['id'=>233, 'testo' =>'La gente dice cose offensive e volgari sul mio conto']);
		Item::create(['id'=>234, 'testo' =>'Non mi sento sotto pressione o stress in questi giorni']);
		Item::create(['id'=>235, 'testo' =>'Mi dà fastidio la gente che mi osserva quando mi trovo fuori, per strada, nei negozi, ecc.']);
		Item::create(['id'=>236, 'testo' =>'Non mi piace sentire gli altri che esprimono la loro opinione sulla vita']);
		Item::create(['id'=>237, 'testo' =>'Evito sempre di prendere medicine o sonniferi senza la prescrizione del medico']);
		Item::create(['id'=>238, 'testo' =>'Quando un uomo è con una donna generalmente pensa a lei da un punto di vista sessuale']);
		Item::create(['id'=>239, 'testo' =>'Se si presentasse l\'occasione potrei essere un buon capo']);
		Item::create(['id'=>240, 'testo' =>'Spesso ho la sensazione come se le cose fossero irreali']);
		Item::create(['id'=>241, 'testo' =>'Qualche volta faccio dei pettegolezzi']);
		Item::create(['id'=>242, 'testo' =>'Qualche volta la sommità della mia testa è molto sensibile']);
		Item::create(['id'=>243, 'testo' =>'Ho paura o disgusto dello sporco']);
		Item::create(['id'=>244, 'testo' =>'Se si presentasse l\'occasione potrei fare cose molto vantaggiose per l\'umanità']);
		Item::create(['id'=>245, 'testo' =>'Se fossi un giornalista mi piacerebbe scrivere cronache teatrali']);
		Item::create(['id'=>246, 'testo' =>'Di solito mi aspetto di ri uscire in quello che faccio']);
		Item::create(['id'=>247, 'testo' =>'Assai spesso mi sento stanco']);
		Item::create(['id'=>248, 'testo' =>'Mi viene spesso detto che sono una testa calda']);
		Item::create(['id'=>249, 'testo' =>'A scuola mi era molto difficile parlare davanti alla classe']);
		Item::create(['id'=>250, 'testo' =>'Spesso mi dispiace di essere così irritabile e di cattivo umore']);
		Item::create(['id'=>251, 'testo' =>' Nessuno lo sa, ma ho tentato di uccidermi']);
		Item::create(['id'=>252, 'testo' =>'Qualcuno controlla la mia mente']);
		Item::create(['id'=>253, 'testo' =>'A scuola i miei voti in condotta usualmente erano brutti']);
		Item::create(['id'=>254, 'testo' =>'Raramente (o mai) mi sento battere forte il cuore o mancare il respiro']);
		Item::create(['id'=>255, 'testo' =>'Non mi disturba in modo particolare veder soffrire gli animali']);
		Item::create(['id'=>256, 'testo' =>'Ho spesso incontrato persone ritenute particolarmente competenti, mentre in realtà non lo erano più di me']);
		Item::create(['id'=>257, 'testo' =>'Ho pensieri strani ed insoliti']);
		Item::create(['id'=>258, 'testo' =>'Sono molto preoccupato dall\'idea di un terremoto']);
		Item::create(['id'=>259, 'testo' =>'Mi piace riparare le serrature']);
		Item::create(['id'=>260, 'testo' =>'Ho spesso lavorato con dei superiori che si prendevano il merito di un buon lavoro e invece addossavano ai loro dipendenti la responsabilità degli errori']);
		Item::create(['id'=>261, 'testo' =>'A volte mi sento come se stessi per andare in pezzi']);
		Item::create(['id'=>262, 'testo' =>'Sono in buona salute fisica come la maggior parte dei miei amici']);
		Item::create(['id'=>263, 'testo' =>'Devo ammettere che talvolta mi sono preoccupato eccessivamente per cose che in realtà non erano importanti']);
		Item::create(['id'=>264, 'testo' =>'Qualcuno ce l\'ha con me']);
		Item::create(['id'=>265, 'testo' =>'Raramente, o mai, ho dolori fisici']);
		Item::create(['id'=>266, 'testo' =>'Ho un problema di droga o di alcool']);
		Item::create(['id'=>267, 'testo' =>'Ho avuto periodi in cui mi sentivo così pieno di energia che per alcuni giorni non avevo bisogno di dormire']);
		Item::create(['id'=>268, 'testo' =>'Mai mi preoccupo del mio aspetto']);
		Item::create(['id'=>269, 'testo' =>'Quando le cose vanno realmente male, so che posso contare sull\'aiuto della mia famiglia']);
		Item::create(['id'=>270, 'testo' =>'Una o più volte nella mia vita ho avuto l\'impressione che qualcuno mi costringesse, ipnotizzandomi, a compiere determinate azioni']);
		Item::create(['id'=>271, 'testo' =>'Mi arrabbio quando qualcuno mi mette fretta']);
		Item::create(['id'=>272, 'testo' =>'Non ho difficoltà ad inghiottire']);
		Item::create(['id'=>273, 'testo' =>'Odo strane cose quando sono solo']);
		Item::create(['id'=>274, 'testo' =>'Di solito ho molta difficoltà a decidere che cosa fare']);
		Item::create(['id'=>275, 'testo' =>'Parecchie volte alla settimana sento come se stesse per accadere qualcosa di spaventoso']);
		Item::create(['id'=>276, 'testo' =>'Quando la gente fa qualcosa che mi fa arrabbiare, faccio in modo che lo sappia']);
		Item::create(['id'=>277, 'testo' =>'Spesso mi accorgo che le mani mi tremano quando provo a fare qualcosa']);
		Item::create(['id'=>278, 'testo' =>'Ogni volta che è possibile evito di stare in mezzo alla folla']);
		Item::create(['id'=>279, 'testo' =>'La maggior parte degli uomini è infedele alla propria moglie di quando in quando']);
		Item::create(['id'=>280, 'testo' =>'Spesso divento confuso e mi dimentico quello che voglio dire']);
		Item::create(['id'=>281, 'testo' =>'I miei familiari mi trattano più da bambino che da adulto']);
		Item::create(['id'=>282, 'testo' =>'Gli obiettivi principali che mi sono posto nella vita sono alla mia portata']);
		Item::create(['id'=>283, 'testo' =>'Parlare dei problemi e delle preoccupazioni con qualcuno è spesso più utile che prendere medicine']);
		Item::create(['id'=>284, 'testo' =>'Ho paura di stare da solo in luoghi vasti e aperti']);
		Item::create(['id'=>285, 'testo' =>'A volte mi sembra di non poter smettere di parlare']);
		Item::create(['id'=>286, 'testo' =>'Non ho paura dei topi']);
		Item::create(['id'=>287, 'testo' =>'Qualcuno ha cercato di influenzare la mia mente']);
		Item::create(['id'=>288, 'testo' =>'Spesso sento di non essere buono come gli altri']);
		Item::create(['id'=>289, 'testo' =>'Mi sono spesso spaventato nel cuore della notte']);
		Item::create(['id'=>290, 'testo' =>'Raramente mi capita di sentire ronzii o rumore nelle orecchie']);
		Item::create(['id'=>291, 'testo' =>'Mai sono così felice come quando sono solo']);
		Item::create(['id'=>292, 'testo' =>'Mi piace lasciare la gente all\'oscuro di quello che sto per fare']);
		Item::create(['id'=>293, 'testo' =>'Di solito sono calmo e non mi agito facilmente']);
		Item::create(['id'=>294, 'testo' =>'Vedo intorno a me cose, animali o persone che gli altri non vedono']);
		Item::create(['id'=>295, 'testo' =>'Non mi preoccupa entrare da solo in una stanza dove ci sono già delle persone che stanno conversando']);
		Item::create(['id'=>296, 'testo' =>'Mi piacerebbe fare il giornalista']);
		Item::create(['id'=>297, 'testo' =>'Una volta alla settimana, o più spesso, sono alticcio, fatto o ubriaco']);
		Item::create(['id'=>298, 'testo' =>'Qualche volta alle elezioni voto per gente di cui so molto poco']);
		Item::create(['id'=>299, 'testo' =>'Mi sento perso quando devo prendere qualche decisione importante']);
		Item::create(['id'=>300, 'testo' =>'Mi piace molto praticare sport violenti (come per esempio il rugby)']);
		Item::create(['id'=>301, 'testo' =>'Una o più zone della mia pelle sono insensibili']);
		Item::create(['id'=>302, 'testo' =>'Mi piace prendere decisioni e assegnare dei compiti ad altri']);
		Item::create(['id'=>303, 'testo' =>'Generalmente mi irrito molto quando la gente interrompe il mio lavoro']);
		Item::create(['id'=>304, 'testo' =>'Nella maggior parte dei matrimoni uno o entrambi i coniugi sono infelici']);
		Item::create(['id'=>305, 'testo' =>'Mi piacerebbe proprio battere un imbroglione con i suoi stessi mezzi']);
		Item::create(['id'=>306, 'testo' =>'Dimentico dove lascio le cose']);
		Item::create(['id'=>307, 'testo' =>'A volte mi vengono in mente pensieri terribili sulla mia famiglia']);
		Item::create(['id'=>308, 'testo' =>'Spesso sul collo mi vengono delle macchie rosse']);
		Item::create(['id'=>309, 'testo' =>'I soldi mi preoccupano molto']);
		Item::create(['id'=>310, 'testo' =>'Le persone non sono molto gentili con me']);
		Item::create(['id'=>311, 'testo' =>'Qualche volta sono sicuro che gli altri sanno quello che sto pensando']);
		Item::create(['id'=>312, 'testo' =>'Quando ero ubriaco, mi è capitato di arrabbiarmi e rompere mobili o piatti']);
		Item::create(['id'=>313, 'testo' =>'Mai ho avuto paralisi o insolita debolezza in qualche muscolo']);
		Item::create(['id'=>314, 'testo' =>'Odio tutta la mia famiglia']);
		Item::create(['id'=>315, 'testo' =>'Non ne posso più di quello che devo fare tutti i giorni e vorrei soltanto lasciar perdere tutto']);
		Item::create(['id'=>316, 'testo' =>'A volte ho dovuto trattare male persone sgarbate o fastidiose']);
		Item::create(['id'=>317, 'testo' =>'Non posso entrare da solo in una stanza buia anche se sono a casa mia']);
		Item::create(['id'=>318, 'testo' =>'A volte mi arrabbio talmente da non capire più cosa mi sta succedendo']);
		Item::create(['id'=>319, 'testo' =>'Qualche volta mi è difficile far valere i miei diritti perché sono molto riservato']);
		Item::create(['id'=>320, 'testo' =>'Certi animali mi innervosiscono']);
		Item::create(['id'=>321, 'testo' =>'Mi piace condurre una trattativa difficile']);
		Item::create(['id'=>322, 'testo' =>'Le critiche o i rimproveri mi feriscono moltissimo']);
		Item::create(['id'=>323, 'testo' =>'Quando sono triste la compagnia degli amici può sempre tirarmi su il morale']);
		Item::create(['id'=>324, 'testo' =>'Dover prendere decisioni importanti mi rende nervoso']);
		Item::create(['id'=>325, 'testo' =>'Qualche volta le barzellette sporche mi divertono']);
		Item::create(['id'=>326, 'testo' =>'Nella maggior parte delle coppie, i coniugi non mostrano grande affetto l\'uno verso l\'altro']);
		Item::create(['id'=>327, 'testo' =>'Sono solito mettercela tutta pur di averla vinta con chi mi contrasta']);
		Item::create(['id'=>328, 'testo' =>'Se mi arrabbio sono sicuro che mi verrà mal di testa']);
		Item::create(['id'=>329, 'testo' =>'A volte mi sono arrabbiato così tanto che mi sono picchiato con qualcuno, facendogli del male']);
		Item::create(['id'=>330, 'testo' =>'A volte mi sembra di sentire pronunciare a voce alta i miei pensieri']);
		Item::create(['id'=>331, 'testo' =>'Quando la vita diventa difficile, mi viene voglia di darmi per vinto']);
		Item::create(['id'=>332, 'testo' =>'Se la gente non ce l\'avesse avuta con me, avrei potuto avere molto più successo']);
		Item::create(['id'=>333, 'testo' =>'Non mi stanco facilmente']);
		Item::create(['id'=>334, 'testo' =>'In questo periodo i miei pensieri sono rivolti sempre più spesso alla morte e alla vita dopo la morte']);
		Item::create(['id'=>335, 'testo' =>'Mi arrabbio con me stesso perché sono così arrendevole con gli altri']);
		Item::create(['id'=>336, 'testo' =>'Riconosco di avere dei difetti che non riuscirò a correggere']);
		Item::create(['id'=>337, 'testo' =>'Mi sono talmente arrabbiato con qualcuno che mi sono sentito come se stessi per esplodere']);
		Item::create(['id'=>338, 'testo' =>'Sono spesso preoccupato per qualcosa']);
	}

}

